name: Build

on:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          sparse-checkout: .github

      - name: Create release
        run: |
          TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
          gh release create "$TAG" --draft --title "Draft Release"

  build:
    needs: create-release
    strategy:
      matrix:
        arch:
          - "aarch64"
          - "host"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Bootstrap & Build toolchain
        run: |
          sudo apt-get install -y debootstrap
          sudo debootstrap focal $HOME/ubuntu20.04-rootfs http://archive.ubuntu.com/ubuntu/
          sudo chroot $HOME/ubuntu20.04-rootfs apt-get update
          sudo chroot $HOME/ubuntu20.04-rootfs apt-get install -y \
                build-essential \
                libc6-dev \
                libpthread-stubs0-dev \
                libstdc++-9-dev \
                libssl-dev \
                zlib1g-dev \
                pkg-config

          export SYSROOT=$HOME/ubuntu20.04-rootfs

          export PKG_CONFIG_DIR=
          export PKG_CONFIG_LIBDIR="$SYSROOT/usr/lib/x86_64-linux-gnu/pkgconfig:$SYSROOT/usr/share/pkgconfig"
          export PKG_CONFIG_SYSROOT_DIR="$SYSROOT"

          export CFLAGS="--sysroot=$SYSROOT -I$SYSROOT/usr/include -O2 -pipe"
          export CXXFLAGS="$CFLAGS"
          export LDFLAGS="--sysroot=$SYSROOT \
            -L$SYSROOT/lib/x86_64-linux-gnu \
            -L$SYSROOT/usr/lib/x86_64-linux-gnu \
            -Wl,--dynamic-linker=/lib64/ld-linux-x86-64.so.2"

          if [[ ${{ matrix.arch }} == host ]]; then
            ./host-toolchain.sh
            mv -v $HOME/iOSToolchain.tar.xz $HOME/iOSToolchain-$(uname -m).tar.xz
          else
            ./cc-toolchain.sh ${{ matrix.arch }}
            mv -v $HOME/iOSToolchain.tar.xz $HOME/iOSToolchain-${{ matrix.arch }}.tar.xz
          fi

      - name: Upload toolchain
        run: |
          TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
          gh release upload "$TAG" $HOME/iOSToolchain*.tar.xz
