name: Build

on:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          sparse-checkout: .github

      - name: Create release
        run: |
          TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
          gh release create "$TAG" --draft --title "Draft Release"

  build:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        arch: ["aarch64", "host"]
        img: ["ubuntu:24.04", "archlinux:base-devel", "fedora:39"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build toolchain
        run: |
          docker run \
          --rm \
          -v $PWD:/workspace \
          -w /workspace \
          ${{ matrix.img }} \
          sh -c "
            set -e
            img="${{ matrix.img }}"
            distro="${img%%:*}"
            if [ "${{ matrix.arch }}" = "host" ]; then
              ./host-toolchain.sh
              mv -v iOSToolchain.tar.xz iOSToolchain-$(uname -m)-$distro.tar.xz
            else
              ./cc-toolchain.sh ${{ matrix.arch }}
              mv -v iOSToolchain.tar.xz iOSToolchain-${{ matrix.arch }}-$distro.tar.xz
            fi
          "

      - name: Upload toolchain
        run: |
          TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
          gh release upload "$TAG" iOSToolchain*.tar.xz
